package model;
// Generated 12-11-2016 03:04:20 PM by Hibernate Tools 4.3.1



/**
 * DetaOrdenVenta generated by hbm2java
 */
public class DetaOrdenVenta  implements java.io.Serializable {


     private Integer idOrdenVenta;
     private CatProducto catProducto;
     private OrdenVenta ordenVenta;
     private byte precio;
     private int cantidad;
     private byte precioLista;
     private String comentarios;

    public DetaOrdenVenta() {
        this.catProducto = new CatProducto();
        this.ordenVenta = new OrdenVenta();
    }

    public DetaOrdenVenta(CatProducto catProducto, OrdenVenta ordenVenta, byte precio, int cantidad, byte precioLista, String comentarios) {
       this.catProducto = catProducto;
       this.ordenVenta = ordenVenta;
       this.precio = precio;
       this.cantidad = cantidad;
       this.precioLista = precioLista;
       this.comentarios = comentarios;
    }
   
    public Integer getIdOrdenVenta() {
        return this.idOrdenVenta;
    }
    
    public void setIdOrdenVenta(Integer idOrdenVenta) {
        this.idOrdenVenta = idOrdenVenta;
    }
    public CatProducto getCatProducto() {
        return this.catProducto;
    }
    
    public void setCatProducto(CatProducto catProducto) {
        this.catProducto = catProducto;
    }
    public OrdenVenta getOrdenVenta() {
        return this.ordenVenta;
    }
    
    public void setOrdenVenta(OrdenVenta ordenVenta) {
        this.ordenVenta = ordenVenta;
    }
    public byte getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(byte precio) {
        this.precio = precio;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public byte getPrecioLista() {
        return this.precioLista;
    }
    
    public void setPrecioLista(byte precioLista) {
        this.precioLista = precioLista;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }




}


