package model;
// Generated 12-11-2016 03:04:20 PM by Hibernate Tools 4.3.1

import java.time.LocalDate;
import java.time.ZoneId;
import static java.time.temporal.ChronoUnit.DAYS;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenVenta generated by hbm2java
 */
public class OrdenVenta implements java.io.Serializable {

    private Integer idOrdenVenta;
    private Cliente cliente;
    private Empleado empleado;
    private EstadoDocumentos estadoDocumentos;
    private Date fecha;
    private Date fechaVence;
    private Date fechaEntrega;
    private String prioridadAlta;
    private String descripcion;
    private String procesado;
    private Set detaOrdenVentas = new HashSet(0);

    private String diasRestantes;

    public OrdenVenta() {
        this.cliente = new Cliente();
        this.empleado = new Empleado();
        this.estadoDocumentos = new EstadoDocumentos();
    }

    public OrdenVenta(Cliente cliente, Empleado empleado, EstadoDocumentos estadoDocumentos, Date fecha, String prioridadAlta, String descripcion) {
        this.cliente = cliente;
        this.empleado = empleado;
        this.estadoDocumentos = estadoDocumentos;
        this.fecha = fecha;
        this.prioridadAlta = prioridadAlta;
        this.descripcion = descripcion;
    }

    public OrdenVenta(Cliente cliente, Empleado empleado, EstadoDocumentos estadoDocumentos, Date fecha, Date fechaVence, Date fechaEntrega, String prioridadAlta, String descripcion, String procesado, Set detaOrdenVentas) {
        this.cliente = cliente;
        this.empleado = empleado;
        this.estadoDocumentos = estadoDocumentos;
        this.fecha = fecha;
        this.fechaVence = fechaVence;
        this.fechaEntrega = fechaEntrega;
        this.prioridadAlta = prioridadAlta;
        this.descripcion = descripcion;
        this.procesado = procesado;
        this.detaOrdenVentas = detaOrdenVentas;
    }

    public Integer getIdOrdenVenta() {
        return this.idOrdenVenta;
    }

    public void setIdOrdenVenta(Integer idOrdenVenta) {
        this.idOrdenVenta = idOrdenVenta;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Empleado getEmpleado() {
        return this.empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    public EstadoDocumentos getEstadoDocumentos() {
        return this.estadoDocumentos;
    }

    public void setEstadoDocumentos(EstadoDocumentos estadoDocumentos) {
        this.estadoDocumentos = estadoDocumentos;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Date getFechaVence() {
        return this.fechaVence;
    }

    public void setFechaVence(Date fechaVence) {
        this.fechaVence = fechaVence;
    }

    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }

    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }

    public String getPrioridadAlta() {
        return this.prioridadAlta;
    }

    public void setPrioridadAlta(String prioridadAlta) {
        this.prioridadAlta = prioridadAlta;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getProcesado() {
        return this.procesado;
    }

    public void setProcesado(String procesado) {
        this.procesado = procesado;
    }

    public Set getDetaOrdenVentas() {
        return this.detaOrdenVentas;
    }

    public void setDetaOrdenVentas(Set detaOrdenVentas) {
        this.detaOrdenVentas = detaOrdenVentas;
    }

    public String getDiasRestantes() {
        LocalDate fechaActual = LocalDate.now();
        java.sql.Date fechaE = (java.sql.Date) this.fechaEntrega;
        Long dias;
        String status = this.estadoDocumentos.getEstado().toUpperCase();

        dias = DAYS.between(fechaActual, fechaE.toLocalDate());

        if (dias < 0 && status != "PENDIENTE") {
            this.diasRestantes = "No aplica";
        } else {
            this.diasRestantes = String.valueOf(dias);
        }
        return diasRestantes;
    }

}
