package model;
// Generated 11-22-2016 07:47:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoCategoria generated by hbm2java
 */
public class TipoCategoria  implements java.io.Serializable {


     private Integer idtipoCategoria;
     private String nombre;
     private String descripcion;
     private Set catProductos = new HashSet(0);

    public TipoCategoria() {
    }

	
    public TipoCategoria(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public TipoCategoria(String nombre, String descripcion, Set catProductos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.catProductos = catProductos;
    }
   
    public Integer getIdtipoCategoria() {
        return this.idtipoCategoria;
    }
    
    public void setIdtipoCategoria(Integer idtipoCategoria) {
        this.idtipoCategoria = idtipoCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCatProductos() {
        return this.catProductos;
    }
    
    public void setCatProductos(Set catProductos) {
        this.catProductos = catProductos;
    }




}


